root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./main ./main.go"
bin = "./main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "docs", "migrations", "bin"]
exclude_file = []
delay = 2000                                                           # Aumenta el delay si usas WSL
stop_on_error = true
log = "air_errors.log"
send_interrupt = true                                                  # Importante para reinicios limpios

[run]
args_bin = []

[log]
time = true

[color]
main = "cyan"
watcher = "green"
build = "yellow"
runner = "magenta"

[misc]
welcome_message = "🚀 Air ejecutando: cmd/app/main.go"
